# Generated by Django 4.2.7 on 2023-11-27 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_invoice_settings_client_clientlogo_client_taxnumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='paymentTerms',
            field=models.CharField(choices=[('7 days', '7 days'), ('14 days', '14 days'), ('30 days', '30 days'), ('60 days', '60 days')], default='14 days', max_length=100),
        ),
        migrations.AlterField(
            model_name='settings',
            name='province',
            field=models.CharField(blank=True, choices=[('Western Cape', 'Western Cape'), ('Gauteng', 'Gauteng'), ('Free State', 'Free State'), ('Limpopo', 'Limpopo')], max_length=100),
        ),
    ]
