# Generated by Django 4.2.7 on 2023-11-30 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_alter_invoice_paymentterms_alter_settings_province'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='town',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='town',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
